commands/install/script, lib/chart-version-bumper.sh
This is required for updating  canary tags in deis-dev charts for slugrunner, slugbuilder, dockerfilebuilder images 
https://github.com/deis/charts/pull/164
=> feat(subimages): update canary tags for subimages

commands/install/script, commands/uninstall/script, lib/config.sh, lib/functions.sh
=> feat(various): rename to reflect current chart and component names

lib/chart-version-bumper.sh
=> fix(chart-version-bumper.sh): tweak sed regex to ignore double quote character

commands/install/script
=> bug(events): really background the kubectl job

lib/functions.sh
thinking it was an error having `deis-router` duplicated in components list... cc @sgoings
=> fix(functions.sh): remove duplicated 'deis-router' entry

commands/install/script, commands/uninstall/script
this should solve most of the false negatives remote end hung up errors
=> feat(slug): pull slugrunner and slugbuilder images

lib/gke.sh
Currently using n1-standard-1 which is 1 VCPU and 3.75GB RAM
Use n1-standard-2 which is 2 VPCU and 7.5GB RAM
=> feat(infra): larger machines for test

lib/functions.sh
Would like to figure out how to test this stuff in CI.
=> Bug + Feature

lib/functions.sh
* avoid xargs and subshell redirection
=> feat(debugging): gather pod descriptions and logs

commands/test/script, lib/functions.sh
=> feat(lib): retrieve junit xml file from e2e tests

lib/deis.sh
refer https://github.com/deis/workflow-e2e/pull/134
=> feat(dns): change xip to nip

commands/test/script
=> fix(commands/test/script): cat all junit-*.xml files into one

commands/bumpver/script, commands/test/script, lib/config.sh
This represents the necessary update to go along with changes in
https://github.com/deis/workflow-e2e/pull/157 and
https://github.com/deis/charts/pull/218
=> feat(commands/test): update test chart name

commands/install/script
=> fix(commands/install): remove slug(run/build)testing cache actions

commands/install/script
This allows us to utilize the chart templating instead of having to sed replace the values in the charts
=> chore(install/script): Set component specific GIT_TAG env vars

commands/bumpver/script, commands/install/script, lib/config.sh
Move if checks for  to
now that logger is in workflow-dev we can stop trying to use the logger chart
=> refactor: adds a few refactors

lib/config.sh
needed to fix up the if statements
=> fix(config): i fail at bash

commands/install/script
=> Revert "chore(install/script): Print out images being used for test run befor…"

commands/install/script, lib/config.sh
fixes #65
it will also cat this file after it was written and grep out the images so we can see those in the CI run
=> chore(install/script): Write pod describes to file

commands/install/script
To avoid https://github.com/helm/helm/issues/430
=> chore(install): Make helm generate a separate command 

commands/install/script, lib/config.sh, lib/functions.sh
Now fetch the namespace, svcs, pods, and daemonsets. Also cat | grep Image:
=> chore(install): Improve kubectl describe

commands/install/script, lib/config.sh, lib/functions.sh
Log the full event format + a know format for post-processing.
Fixes `Error from server: pods "UTC" not found` in test runs.
=> bug(logs): k8s 1.2 event format changed, fix Pod log fetcher

README.md
I have gotten a lot of questions about chart-mate's role and why it exists. Hopefully this presents a good start to explaining what it is and why it needs to exist for now.
/cc @jchauncey @vdice @krancour @arschles @helgi
After this gets merged I'd like to see it moved into the deis organization now that we have the purpose/caveats section filled out a bit.
=> feat(README): improve purpose and explain actions
